### PR TITLE
Fix for windows

### PR DESCRIPTION
**Pull request by nivpenso**

### CODE REVIEW

**Comment by mmoreram** [comment]
@nivpenso I already merged this PR. If you want to add more changes, please rebase your branch!

Thanks!

**Comment by nivpenso** [comment]
Thanks for the reply @mmoreram 
Done. Please let me know if there anything need

**Comment by mmoreram** [comment]
The thing we need in all commits is to have 1 single commit on top of master. You can do this by rebasing first your work with master and, after that, squashing your work to have only 1 single commit.

- https://www.atlassian.com/git/tutorials/merging-vs-rebasing
- https://www.devroom.io/2011/07/05/git-squash-your-latests-commits-into-one/

Thanks!

**Comment by nivpenso** [comment]
No problem,
I'll create a new PR from a new branch it will be shorter... closing this one

**Pull request closed without merging**
